name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
tool = input("Favorite Cybersecurity Tool: ")

print("===================================")
print("        USER PROFILE")
print("===================================")
print()
print(f"Name : {name}")
print(f"Age : {age}")
print(f"City : {city}")
print(f"Favorite Tool : {tool}")
print()
print(f"Next year you will be {age + 1} years old.")
print()
print("Thank you for using this program!")